# Generated by Django 4.2 on 2023-07-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parserconfig',
            options={'verbose_name': 'Налаштування', 'verbose_name_plural': 'Налаштування'},
        ),
        migrations.AlterModelOptions(
            name='parserresult',
            options={'verbose_name': 'Результат пошуку', 'verbose_name_plural': 'Результат пошуку'},
        ),
        migrations.AlterModelOptions(
            name='telegramconfig',
            options={'verbose_name': 'Telegram', 'verbose_name_plural': 'Telegram'},
        ),
        migrations.AddField(
            model_name='parserresult',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
