# Generated by Django 4.2 on 2023-07-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_parserconfig_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parserresult',
            name='flag',
        ),
        migrations.AddField(
            model_name='parserconfig',
            name='flag',
            field=models.BooleanField(default=False, verbose_name='Перша перевірка'),
        ),
    ]
