# Generated by Django 4.2 on 2023-07-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_parserresult_flag_parserconfig_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='parserresult',
            name='flag',
            field=models.BooleanField(default=False, verbose_name='Надісланий в чат'),
        ),
    ]
