# Generated by Django 4.2 on 2023-07-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_parserresult_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parserresult',
            name='flag',
            field=models.BooleanField(default=False, verbose_name='Відправлено в чат'),
        ),
    ]
